### ISSUE TITLE
Bad INstall directions

### ISSUE THREAD

**Issue by muschellij2** [Bigsealion/REUnet#1]
Trying to install REUnet:
https://github.com/Bigsealion/REUnet/blob/master/install_REUnet.py#L23 pulls from an environment variable `nnUNet_preprocessed`?  What is this for?
```
Copy /Users/johnmuschelli/Dropbox/Packages/REUnet/nnUNet_preprocessed to None
Traceback (most recent call last):
  File "/Users/johnmuschelli/Dropbox/Packages/REUnet/./install_REUnet.py", line 59, in <module>
    main()
  File "/Users/johnmuschelli/Dropbox/Packages/REUnet/./install_REUnet.py", line 36, in main
    copytree(REU_preprocessed_dir, preprocessed_dir)  # preprocesssing
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnmuschelli/Dropbox/Packages/REUnet/./install_REUnet.py", line 14, in copytree
    d = os.path.join(dst, item)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

cannot create `nnUNet_predict_sam` at all.

Also https://github.com/Bigsealion/REUnet/blob/3a37b172bdb7aa1484d64d0a58354dbf1fe6a471/download_REUnet_trained_models.py#L25 pulls from the `RESULTS_FOLDER` environment variable, which isn't documented anywhere.

I've found this to be helpful for installing the correct nnUNET:
```
conda create -n reunet
conda activate reunet
rm -rf deps/nnUNet
mkdir -p deps
git clone --branch v1.7.0 --single-branch git@github.com:MIC-DKFZ/nnUNet.git deps/nnUNet
cd deps/nnUNet
cp ../../utils/nnU_setup_example/setup.py setup.py
pip install -e .
cd ../../
rm -rf deps
```

This is helpful for downloading the trained models:
```
mkdir -p models
RESULTS_FOLDER=./models python ./download_REUnet_trained_models.py
```

And lastly, this should work, to create `nnUNet_predict_sam`, but it does not:
```
mkdir -p processed
nnUNet_preprocessed=./processed python install_REUnet.py
```

**Comment by Bigsealion** [comment]
Hello,

Thank you for your interest in `REUnet`!

Please note that `REUnet` is built on `nnUNet`, so it’s necessary to install `nnUNet` first. The environment variables `nnUNet_preprocessed` and `RESULTS_FOLDER` are required by `nnUNet`. You can refer to the setup instructions in the following [link](https://github.com/MIC-DKFZ/nnUNet/blob/v1.7.0/documentation/setting_up_paths.md).

If you encounter any other installation issues, feel free to reach out for further assistance!

**Comment by muschellij2** [comment]
here is a reproducible example of how this fails to install REUnet:

# Setup
Clone REUnet, create a condaenv, install correct version of nnunet with REUnet setup.py

```bash
cd $TMPDIR
git clone https://github.com/Bigsealion/REUnet
cd REUnet
# if already have reunet conda env
# conda remove -n reunet --all
conda create -n reunet -y
conda activate reunet
conda install -y pip
rm -rf deps/nnUNet
mkdir -p deps
git clone --branch v1.7.0 --single-branch git@github.com:MIC-DKFZ/nnUNet.git deps/nnUNet
cd deps/nnUNet
cp ../../utils/nnU_setup_example/setup.py setup.py
pip install -e .
cd ../../
pip freeze | grep nnunet
pip install matplotlib tqdm
```


# Download Models
```bash
mkdir -p models
export RESULTS_FOLDER=./models
python ./download_REUnet_trained_models.py
```

# Try to install REUnet
```bash
mkdir -p test_processed
export nnUNet_preprocessed=./test_processed
python ./install_REUnet.py
```

And here is the output of `python ./install_REUnet.py`:

```
Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Copy /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnunet to /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet
Copy /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnUNet_preprocessed to ./test_processed
nnu dir: /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet
REU_model_dir: /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnunet
REU_preprocessed_dir: /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnUNet_preprocessed
REUnet is installed
usage: install_REUnet.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: install_REUnet.py --help [cmd1 cmd2 ...]
   or: install_REUnet.py --help-commands
   or: install_REUnet.py cmd --help

error: no commands supplied
```

And trying to pass in a `cmd`/`install`:

```bash
python ./install_REUnet.py install
```

```
Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Copy /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnunet to /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet
Copy /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnUNet_preprocessed to ./test_processed
nnu dir: /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet
REU_model_dir: /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnunet
REU_preprocessed_dir: /private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/nnUNet_preprocessed
REUnet is installed
error: Multiple top-level packages discovered in a flat-layout: ['deps', 'models', 'nnunet', 'example_data', 'test_processed', 'nnUNet_preprocessed'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

**Comment by Bigsealion** [comment]
The error was caused by a conflict in the setup, which has now been resolved.

If you have any further questions, feel free to reach out for further assistance.

**Comment by muschellij2** [comment]
Installs fine, thank you.

Still fails to predict:
```
(reunet) macbook-pro-18:REUnet johnmuschelli$ ip=./example_data/image_be/
(reunet) macbook-pro-18:REUnet johnmuschelli$ mkdir -p output
(reunet) macbook-pro-18:REUnet johnmuschelli$ op=./output/
(reunet) macbook-pro-18:REUnet johnmuschelli$ fold=0
(reunet) macbook-pro-18:REUnet johnmuschelli$ nnUNet_predict_sam -i ${ip} -o ${op} -t 607 -m 3d_fullres -f ${fold} -chk model_best -tr nnUNetTrainerV2_REUNet -p nnUNetPlans_REUNet_v2.1 --save_npz


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/johnmuschelli/miniconda3/envs/reunet/bin/nnUNet_predict_sam", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict_sam')())
  File "/Users/johnmuschelli/miniconda3/envs/reunet/bin/nnUNet_predict_sam", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam_simple.py", line 17, in <module>
    import torch
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/segmentation_export.py:34: SyntaxWarning: invalid escape sequence '\%'
  """

/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/training/network_training/nnUNetTrainer.py:611: SyntaxWarning: invalid escape sequence '\%'
  """There is a problem with python process communication that prevents us from communicating obejcts
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/training/data_augmentation/pyramid_augmentations.py:26: SyntaxWarning: invalid escape sequence '\%'
  """
nnUNet_raw_data_base is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict.py:63: SyntaxWarning: invalid escape sequence '\%'
  """There is a problem with python process communication that prevents us from communicating obejcts
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict.py:246: SyntaxWarning: invalid escape sequence '\%'
  """There is a problem with python process communication that prevents us from communicating obejcts
using model stored in  ./models/nnUNet/3d_fullres/Task607_HemaSegRawBrainAll977/nnUNetTrainerV2_REUNet__nnUNetPlans_REUNet_v2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['UNE00281']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, [0]
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/training/network_training/nnUNetTrainerCascadeFullRes.py:227: SyntaxWarning: invalid escape sequence '\%'
  """There is a problem with python process communication that prevents us from communicating obejcts
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/training/network_training/nnUNetTrainerV2_CascadeFullRes.py:282: SyntaxWarning: invalid escape sequence '\%'
  """There is a problem with python process communication that prevents us from communicating obejcts
/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/training/network_training/nnUNetTrainerV2_DDP.py:524: SyntaxWarning: invalid escape sequence '\%'
  """There is a problem with python process communication that prevents us from communicating obejcts
2024-09-09 12:14:57.767500: Using dummy2d data augmentation
using the following model files:  ['./models/nnUNet/3d_fullres/Task607_HemaSegRawBrainAll977/nnUNetTrainerV2_REUNet__nnUNetPlans_REUNet_v2.1/fold_0/model_best.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "/Users/johnmuschelli/miniconda3/envs/reunet/bin/nnUNet_predict_sam", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict_sam')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam_simple.py", line 222, in main
    predict_and_segment_ability_map_from_folder(
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam.py", line 330, in predict_and_segment_ability_map_from_folder
    return predict_cases_and_segment_ability_map(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam.py", line 104, in predict_cases_and_segment_ability_map
    for preprocessed in preprocessing:
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict.py", line 109, in preprocess_multithreaded
    pr.start()
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'BasicResidualBlock.__init__.<locals>.<lambda>'
```

Running on Python 3.12.4 
```python
>>> import torch
torch._C._get_default_device()
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

>>> torch._C._get_default_device()
'cpu'
>>> torch._C._get_default_device()
'cpu'
```

Will try on Python 3.9.7 and rerun

**Comment by muschellij2** [comment]
Still fails on Python 3.9.7:
```
nnUNet_predict_sam -i ${ip} -o ${op} -t 607 -m 3d_fullres -f ${fold} -chk model_best -tr nnUNetTrainerV2_REUNet -p nnUNetPlans_REUNet_v2.1 --save_npz


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/johnmuschelli/miniconda3/envs/reunet/bin/nnUNet_predict_sam", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict_sam')())
  File "/Users/johnmuschelli/miniconda3/envs/reunet/bin/nnUNet_predict_sam", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam_simple.py", line 17, in <module>
    import torch
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
nnUNet_raw_data_base is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
using model stored in  ./models/nnUNet/3d_fullres/Task607_HemaSegRawBrainAll977/nnUNetTrainerV2_REUNet__nnUNetPlans_REUNet_v2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['UNE00281']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, [0]
2024-09-09 12:39:23.208886: Using dummy2d data augmentation
using the following model files:  ['./models/nnUNet/3d_fullres/Task607_HemaSegRawBrainAll977/nnUNetTrainerV2_REUNet__nnUNetPlans_REUNet_v2.1/fold_0/model_best.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "/Users/johnmuschelli/miniconda3/envs/reunet/bin/nnUNet_predict_sam", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict_sam')())
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam_simple.py", line 222, in main
    predict_and_segment_ability_map_from_folder(
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam.py", line 330, in predict_and_segment_ability_map_from_folder
    return predict_cases_and_segment_ability_map(
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict_sam.py", line 104, in predict_cases_and_segment_ability_map
    for preprocessed in preprocessing:
  File "/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/REUnet/deps/nnUNet/nnunet/inference/predict.py", line 109, in preprocess_multithreaded
    pr.start()
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/johnmuschelli/miniconda3/envs/reunet/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'BasicResidualBlock.__init__.<locals>.<lambda>'
```

```
(reunet) macbook-pro-18:REUnet johnmuschelli$ python
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by Bigsealion** [comment]
My test system environment is CentOS 7. I'm not sure if you are using Linux to run REUnet. I hope you can provide more information. Thank you.

**Comment by muschellij2** [comment]
I'm using MacOS Sonoma 14.4.1.

**Comment by Bigsealion** [comment]
We sincerely apologize, but we do not have the resources to test whether REUnet can work on MacOS. So far, we have only tested it on CentOS 7 and confirmed that it runs properly. Therefore, if possible, you might consider using a Linux system to run REUnet.

**Comment by muschellij2** [comment]
Can you not use GitHub actions to confirm this does not work properly?

**Comment by Bigsealion** [comment]
I'm not entirely sure if I fully understood your question, but I can confirm that I tested whether REUnet could run by installing and running it from scratch on our own server. 

Specifically, our server runs on CentOS 7, so I created a new account on this server, installed REUnet from the ground up, and was able to run it successfully. 

However, unfortunately, since I don't have a MacOS device, I cannot verify its availability on MacOS.

**Comment by muschellij2** [comment]
Your project is on GitHub.  GitHub has a continuous integration service named GitHub actions: https://docs.github.com/en/actions.  GitHub actions can run a MacOS runner to check that this works on MacOS.

**Comment by Bigsealion** [comment]
The free storage space on GitHub Actions is only 500MB, which prevents me from using this method to debug

However, I noticed that your error is caused by numpy, and your version (2.1.1) is different from the version I used (2.0.2). Therefore, I suggest you try adjusting the numpy version to 2.0.2.

For reference, here is the output of `conda list`:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
argparse                  1.4.0                    pypi_0    pypi
batchgenerators           0.25                     pypi_0    pypi
ca-certificates           2024.7.2             h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2024.8.30                pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dicom2nifti               2.4.11                   pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fsspec                    2024.9.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
idna                      3.8                      pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
importlib-resources       6.4.4                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.4.4                h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
linecache2                1.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
medpy                     0.5.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  3.2.1                    pypi_0    pypi
nibabel                   5.2.1                    pypi_0    pypi
nnunet                    1.7.0                     dev_0    <develop>
numpy                     2.0.2                    pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openssl                   3.0.15               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2             py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pydicom                   2.4.4                    pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
python                    3.9.19               h955ad1f_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.9.0.post0              pypi_0    pypi
python-gdcm               3.0.24.1                 pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.32.3                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
setuptools                72.1.0           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
simpleitk                 2.4.0                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sympy                     1.13.2                   pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
tk                        8.6.14               h39e8969_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch                     2.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
traceback2                1.4.0                    pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
unittest2                 1.1.0                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
wheel                     0.43.0           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.4.6                h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zipp                      3.20.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```
